### ISSUE TITLE
Support PDFJS v3.3.122

### ISSUE THREAD

**Issue by melloware** [react-pdf-viewer/react-pdf-viewer#1415]
Support: https://github.com/mozilla/pdf.js/releases/tag/v3.3.122

**Comment by phuocng** [comment]
@melloware @spaguette @titouan42
The pdf-js 3.3.122 is supported in the latest version (3.11.0). I also updated the [documentation](https://react-pdf-viewer.dev/docs/getting-started/)

**Comment by spaguette** [comment]
I'm using Vite with React, and it looks like when I close the PDF Viewer (3.11.0), with PDFJS v3.3.122 it throws this error:

```
Uncaught TypeError: Cannot perform %TypedArray%.prototype.every on a detached ArrayBuffer
    at Uint8Array.every (<anonymous>)
    at isSameUrl (core.js:3952:43)
    at core.js:3983:14
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:9)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
```

And then
```
The above error occurred in the <Viewer> component:
    at Viewer (http://localhost:3000/node_modules/.vite/deps/chunk-47WVVCP2.js?v=484d6073:28490:29)
    ...
```

This doesn't happen with the previous PDFJS version though (v3.2.146), otherwise same setup 🤔 I wonder if I'm missing something there, and if anybody else also experiences this.

**Comment by sirkrisp** [comment]
getting the same error. any updates? Thanks!
