### ISSUE TITLE
Bug: search + highlight plugins - duplicate UI

### ISSUE THREAD

**Issue by shoaziz-shorakhimov** [react-pdf-viewer/react-pdf-viewer#1451]
## About bug:

We've implemented a pdf-viewer in our application recently, and faced a bug. Basically, when you highlight the text in the search input of `search` plugin in a specific way, the UI for the search panel starts duplicating itself, showing kinda glitchy history of previous searches. More details below.

**How it looks like:**

https://user-images.githubusercontent.com/74359021/224018332-ea7721cb-42d7-46fc-82eb-d8e63029943e.mov

**Example/sandbox:** https://1gz5en.csb.app/

**Steps to reproduce:**

1. Launch the example
2. Open search
3. Write something in the search input
4. Highlight it **with mouse** from right to left
5. Make sure to drop your mouse directly on top of the viewer

**Results:**

For each such repetition, a frozen duplicate of search-popup will appear. I say frozen because navigation arrows and close button don't work on them. Additionally, an error in the console appears (which seems to be causing the issue itself):
```
Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 31.
    at getRectFromOffsets (https://1gz5en.csb.app/node_modules/@react-pdf-viewer/highlight/lib/cjs/highlight.js:375:11)
    at HTMLDivElement.onMouseUpHandler (https://1gz5en.csb.app/node_modules/@react-pdf-viewer/highlight/lib/cjs/highlight.js:536:35)
```

## Some interesting notes found during investigation, that might help:

- Even though the UI is buggy for the `search` plugin, bug itself seems to be related to the `highlight` plugin. At least it takes part in the resulting bug. That's according to the console error, and to the fact that without highlight plugin everything works fine.
- Highlighting from right to left is not actually important. It was just easier to explain reproducing steps this way, and is a more natural action which can be done by real users. And in fact, this action was what we initially thought is causing the bug.
- Absolute positioning and styles on the search toolbar are also not important. Again, just easier to reproduce the bug naturally when the search is on top of the viewer, and again more natural setup when the bug can be met by users.
- From the logs and a bit of dive-in into the code, I have an assumption that it has something to do with at least mouse-up event listener of the `highlight` plugin. The stack trace leads there. Also, it seemed to me that some logic can be found in this - `highlight` seems to expect text highlights only inside the viewer, but in this case we start highlighting from completely different place. Another evidence also support this assumption. Try starting the highlight from anything on the page (even not `search` this time), and ending it on the viewer's text. Some errors should start appearing in the console. Although this time you won't see a UI glitch, and potentially the errors will be a bit different:
  - Start highlighting from another text (not search input) in the search popup:
    ```
    Uncaught DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 7.
        at getRectFromOffsets (https://1gz5en.csb.app/node_modules/@react-pdf-viewer/highlight/lib/cjs/highlight.js:374:11)
        at HTMLDivElement.onMouseUpHandler (https://1gz5en.csb.app/node_modules/@react-pdf-viewer/highlight/lib/cjs/highlight.js:536:35)
    ```
  - Start highlighting from "Some random text" on above the viewer:
    ```
    Uncaught RangeError: Invalid array length
        at getRectBetween (highlight.js:503:20)
        at HTMLDivElement.onMouseUpHandler (highlight.js:547:32)
    ```

The last error type also have made me think that this issue might be related to #1244. That issue is also about the same error type, and is also related to the `highlight` plugin.

**Comment by shoaziz-shorakhimov** [comment]
@phuocng hello. Are there any news about this? Were you able to take a look at this and/or confirm the bug?

**Comment by nsantos16** [comment]
@phuocng Same issue here, any estimate for fixing this?

**Comment by toteberbel** [comment]
Same issue here, but when I try to select text from the PDF.
![image](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/59628952/624f7d74-4110-462c-9e28-6e3774b10361)

**Comment by phuocng** [comment]
It's a known issue.
Will make this a high priority.

**Comment by iamrraj** [comment]
Hey @phuocng  is there any update for this issue ?
