### ISSUE TITLE
ERROR Illegal invocation

### ISSUE THREAD

**Issue by charmstead** [react-pdf-viewer/react-pdf-viewer#1552]
I'm getting the following error while PDF is trying to render

```
ERROR
Illegal invocation
TypeError: Illegal invocation
    at getAscent (http://localhost:3000/static/js/vendors-node_modules_react-pdf-viewer_default-layout_lib_index_js-node_modules_react-pdf-view-83fedd.chunk.js:38414:32)
    at appendText (http://localhost:3000/static/js/vendors-node_modules_react-pdf-viewer_default-layout_lib_index_js-node_modules_react-pdf-view-83fedd.chunk.js:38481:41)
    at TextLayerRenderTask._processItems (http://localhost:3000/static/js/vendors-node_modules_react-pdf-viewer_default-layout_lib_index_js-node_modules_react-pdf-view-83fedd.chunk.js:38910:17)
    at TextLayerRenderTask._render (http://localhost:3000/static/js/vendors-node_modules_react-pdf-viewer_default-layout_lib_index_js-node_modules_react-pdf-view-83fedd.chunk.js:38969:22)
    at Object.renderTextLayer (http://localhost:3000/static/js/vendors-node_modules_react-pdf-viewer_default-layout_lib_index_js-node_modules_react-pdf-view-83fedd.chunk.js:39073:16)
    at http://localhost:3000/static/js/vendors-node_modules_react-pdf-viewer_default-layout_lib_index_js-node_modules_react-pdf-view-83fedd.chunk.js:3989:48
```

**Comment by phuocng** [comment]
@charmstead 
Does the issue happen with any documents? If it only happens with a specific document, can you give me the sample document?

**Comment by charmstead** [comment]
i'm not sure if it's almost any document. I have attached a sample document i experienced it with
[invoice_2b12698f5d028b021952.pdf](https://github.com/react-pdf-viewer/react-pdf-viewer/files/12184742/invoice_2b12698f5d028b021952.pdf)

**Comment by charmstead** [comment]
Hi @phuocng Were you able to review this?
