### ISSUE TITLE
TypeError: Cannot perform %TypedArray%.prototype.every on a detached ArrayBuffer

### ISSUE THREAD

**Issue by snake-py** [react-pdf-viewer/react-pdf-viewer#1604]
Hello, 

I am trying to use this lib, however everytime I load in a pdf which has more than two pages, and I scroll to the second page I get the following error:

```
Uncaught TypeError: Cannot perform %TypedArray%.prototype.every on a detached ArrayBuffer
    at Uint8Array.every (<anonymous>)
    at isSameUrl (core.js:4437:43)
    at core.js:4475:14
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
```

followed by

```
The above error occurred in the <Viewer> component:

    at Viewer (http://localhost:3000/node_modules/.vite/deps/chunk-GQOUK6JH.js?v=6f723487:20533:29)
    at Worker2 (http://localhost:3000/node_modules/.vite/deps/chunk-GQOUK6JH.js?v=6f723487:20618:25)
    at div
    at PdfComponent (http://localhost:3000/src/UI/widgets/DocumentViewWidget/DocumentViewWidget.tsx?t=1694074923631:115:3)
    at div
    at http://localhost:3000/@fs/home/fabio/Desktop/workdigital/packages/component-library-react/dist/index.es.js:4847:20
    at DocumentViewWidget (http://localhost:3000/src/UI/widgets/DocumentViewWidget/DocumentViewWidget.tsx?t=1694074923631:39:3)
    at DocumentView (http://localhost:3000/src/UI/customer-services/services/documentView/components/DocumentView.tsx?t=1694074923631:28:7)
```
followed by a second

```
Uncaught TypeError: Cannot perform %TypedArray%.prototype.every on a detached ArrayBuffer
    at Uint8Array.every (<anonymous>)
    at isSameUrl (core.js:4437:43)
    at core.js:4475:14
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
```

This is how I use it:

```ts


const PdfComponent: FC<TPdfComponentProps> = ({
  getFilePluginInstance,
  documentAsUint8Array,
  printPluginInstance,
  renderPage
}) => {
  return (
    <div className="pdf-viewer-container">
      {documentAsUint8Array ? (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@3.4.120/build/pdf.worker.min.js">
          <Viewer
            fileUrl={import.meta.env.STORYBOOK ? 'public/test.pdf' : documentAsUint8Array}
            plugins={[printPluginInstance, getFilePluginInstance]}
            renderPage={renderPage}
            defaultScale={SpecialZoomLevel.PageWidth} // Set the default scale
          />
        </Worker>
      ) : (
        <ProgressSpinner className="my-8" />
      )}
    </div>
  );
};


/// in the component where this is rendered I do:


const DocumentViewWidget: FC<TDocumentViewWidgetProps> = ({
  handleClose,
  handleSave,
  handleLoadError,
  documentId,
  setFileName
}) => {
  const [documentAsUint8Array, setDocumentAsUint8Array] = useState<Uint8Array>(); 
  const getFilePluginInstance = getFilePlugin();
  const printPluginInstance = printPlugin();

  useEffect(() => {
    openDocument(documentId);
  }, []);

  const openDocument = async (documentId: string) => {
    try {
      const documentAsBase64 = await getDocumentAsBase64(documentId);
      const uint8Array = base64ToUint8Array(documentAsBase64.document);
      setDocumentAsUint8Array(uint8Array);
      setFileName(documentAsBase64.filename);
    } catch (error: unknown) {
      handleLoadError(error as Error);
    }
  };

return (
      <PdfComponent
        documentAsUint8Array={documentAsUint8Array}
        getFilePluginInstance={getFilePluginInstance}
        renderPage={renderPage}
        printPluginInstance={printPluginInstance}
      />
)};

**Comment by phuocng** [comment]
What's your browser and version?

**Comment by snake-py** [comment]
I am actually getting the same error on your example page for uint array

![image](https://github.com/react-pdf-viewer/react-pdf-viewer/assets/59285387/f27962ba-3582-4011-9740-adb195558b37)


It always happens if I scroll up and down multiple times. 

I am using chrome in my code base I have installed the newst version can check on monday again. But since I am seeing it in the example, I guess it is a bug of the newest version?

**Comment by snake-py** [comment]
@phuocng any updates on this?

**Comment by YourAverageTechBro** [comment]
> I was running into this issue but adding the read-pdf-viewer css sheets seemed to fix it. Specifically,
> 
> ```
> import "react-pdf/dist/esm/Page/AnnotationLayer.css";
> import "react-pdf/dist/esm/Page/TextLayer.css";
> import "@react-pdf-viewer/core/lib/styles/index.css";
> import "@react-pdf-viewer/default-layout/lib/styles/index.css";
> ```
> 
> not too sure why this fixed the error, but it worked for me 🤷

Just kidding, I am still getting the issue.

**Comment by ReubenJCarter** [comment]
I'm getting this issue as well

**Comment by snake-py** [comment]
To everyone who comes here. Since the arrayyBuffer seems to be broken. We now transfroming the file to a base64 string and passing that to the Component

```
      <PDFComponent
        documentAsBase64={documentAsBase64}
        />
```

**Comment by sirkrisp** [comment]
downgrading to "pdfjs-dist": "2.12.313" resolves this issue, too. However, hope this issue can be properly solved soon.

**Comment by stv8** [comment]
Also experiencing this and had to switch over to the base64 solution that @snake-py suggested (which worked great) but it would be nice to fix the array version.
